### ISSUE TITLE
[test] 无法访问网站

### ISSUE THREAD

**Issue by xrkffgg** [actions-cool/issues-helper#1]
2211
is
网站挂了

**Comment by xrkffgg** [comment]
Currently at actions-cool/issue-helper. And this is default comment.

**Comment by xrkffgg** [comment]
Currently at actions-cool/issue-helper. And this is default comment.

**Comment by xrkffgg** [comment]
Currently at actions-cool/issue-helper. And this is default comment.

**Comment by xrkffgg** [comment]
Currently at actions-cool/issue-helper. And this is default comment.
Currently at actions-cool/issue-helper. And this is default comment.
Currently at actions-cool/issue-helper. And this is default comment.
Currently at actions-cool/issue-helper. And this is default comment.

**Comment by xrkffgg** [comment]
Currently at actions-cool/issue-helper. And this is default comment.

**Comment by xrkffgg** [comment]
Currently at actions-cool/issue-helper. And this is default comment.

**Comment by HuaRin** [comment]
1

**Comment by HuaRin** [comment]
this

**Comment by xrkffgg** [comment]
is ass

**Comment by xrkffgg** [comment]
22221

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/actions-cool/issues-helper/issues/2

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/actions-cool/issues-helper/issues/2
122
