### ISSUE TITLE
[Feature] Exclude contributors

### ISSUE THREAD

**Issue by pkuczynski** [actions-cool/issues-helper#102]
### 🥰 需求描述 Description of Requirement

I would like to use `create-comment` but don't do that when an issue is created by someone who is already a contributor in this repository.

### 🧐 解决方案 Solution

Add new option: `except-for` with an array of following options:
* @codeowners
* @contributors
* user123

**Comment by xrkffgg** [comment]
OK i will support

**Comment by xrkffgg** [comment]
@pkuczynski 

I thought about it, this `create-comment` will keep purely functional.

You can use https://github.com/actions-cool/check-user-permission to check if a user is contributor.

And according to `check-result` to decide what to do next.

If have any questions comment below.

**Comment by xrkffgg** [comment]
@Shinigami92
