### ISSUE TITLE
[Question] Help

### ISSUE THREAD

**Issue by lingcoder** [actions-cool/issues-helper#111]
### 🧐 问题描述 Problem Description

我想通过定时任务给issue打inactive标签，但是要先判断issue至少已经被打上一个非bug标签。
如果issue没任何标签，则不处理。这么做是为了让每个issue至少经过社区打过标签后才被issue-helper处理。
请问这样的条件该怎么写呢

**Comment by xrkffgg** [comment]
加群直接问~
