### ISSUE TITLE
[BUG] Report bug

### ISSUE THREAD

**Issue by oliviertassinari** [actions-cool/issues-helper#115]
### 🐛 Bug 描述 Bug description

mark-duplicate is not updating the labels

### 🏞 期望结果 Desired result

mark-duplicate should update the labels

### 🚑 其他信息 Other information

The bug was noticed here: https://github.com/mui/material-ui/issues/34081#issuecomment-1231621890

**Comment by xrkffgg** [comment]
i will see

**Comment by xrkffgg** [comment]
v3.2.1 has been released and v3 has been synced. 

You don't need to do extra operations, if has other problems, welcome to report.

**Comment by oliviertassinari** [comment]
@xrkffgg Awesome, thanks! I wasn't crazy :)
