### ISSUE TITLE
[Feature] 维护一份文档

### ISSUE THREAD

**Issue by xrkffgg** [actions-cool/issues-helper#119]
### 🥰 需求描述 Description of Requirement

现有 readme 和 网站 文档是分开单独维护的，维护一份

### 🧐 解决方案 Solution

主要维护 readme ，用脚本同步 网站

**Comment by Wxh16144** [comment]
我可以帮忙升级 dumi@2，然后用 [embed](https://d.umijs.org/guide/markdown#embed) 这个功能来实现，如果可以, 请指给我~

**Comment by xrkffgg** [comment]
@Wxh16144 Welcome~
