### ISSUE TITLE
[BUG] "Cannot read property 'toLowerCase' of null" - empty issue bodies cause error when using 'check-issue'

### ISSUE THREAD

**Issue by madmansn0w** [actions-cool/issues-helper#120]
### 🐛 Bug 描述 Bug description

When using `check-issue` - `body-includes` on an issue that has an empty body, the workflow fails with error:
`Error: [🚨 AC] Cannot read property 'toLowerCase' of null`

### 🏞 期望结果 Desired result

Desired result is that issues with empty body content can be reported as boolean. 

### 🚑 其他信息 Other information
Github "Convert to Issue" for task list items yields empty issues, which will break the above functionality.

**Comment by xrkffgg** [comment]
I will check

**Comment by madmansn0w** [comment]
I was able to get it working - previously I was using `body-includes: "### Some Title"` as a check, and since the issue was empty, the result was the OP error. Once I changed it to  `body-includes: ""`, it started working.

**Comment by madmansn0w** [comment]
This is the change needed: (` content?.toLowerCase().includes(item));`)

Original
```javascript
export const matchKeyword = (content: string = '', keywords: string[]): boolean => {
  return !!keywords.find(item => content.toLowerCase().includes(item));
};
```

Revision:
```javascript
export const matchKeyword = (content: string = '', keywords: string[]): boolean => {
  return !!keywords.find(item => content?.toLowerCase().includes(item));
};
```

**Comment by xrkffgg** [comment]
@madmansn0w welcome PR ~

**Comment by madmansn0w** [comment]
Sure -- Give me some time and I'll send it your way.
