### ISSUE TITLE
[BUG] Warning: The `set-output`

### ISSUE THREAD

**Issue by wjz304** [actions-cool/issues-helper#124]
### 🐛 Bug 描述 Bug description

Run actions-cool/issues-helper@v3
....
----] success!

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### 🏞 期望结果 Desired result
不要报 Warning。

**Comment by xrkffgg** [comment]
有兴趣来个 PR 么

**Comment by wjz304** [comment]
不太会js，虽然能看懂，但是不知道咋调试😢
