### ISSUE TITLE
[BUG] Report bug

### ISSUE THREAD

**Issue by caco3** [actions-cool/issues-helper#130]
We where using v2 and it worked well.

But now it stopped working with following error:
```
Run actions-cool/issues-helper@v2
  with:
    actions: remove-labels
    labels: bot-reply Logfile
    token: ***
Error: Not Found
```
![grafik](https://user-images.githubusercontent.com/1783586/209704525-8e420669-984e-40de-954c-3a317b867384.png)

So I tried v3, but that again shows another error:
```

Run actions-cool/issues-helper@v3
Warning: [🎃 AC] 'issue-number' is missing or this action not needed yet!
[📝 AC] [Init] [caco3/AI-on-the-edge-device => undefined]
Error: [🚨 AC] Not Found
```
![grafik](https://user-images.githubusercontent.com/1783586/209704659-588b26ae-c514-40c8-9003-8dec62fc82d8.png)

**Comment by xrkffgg** [comment]
Can you send the yml to have a look?
