### ISSUE TITLE
[Feature] 功能建议

### ISSUE THREAD

**Issue by sejust** [actions-cool/issues-helper#157]
### 🥰 需求描述 Description of Requirement
我现在想按照时间标记issues，每天运行一次。
比如： 不活跃 3天， 1周，1月，半年。

我用的  *check-inactive*

如果用 inactive-day，标记为3天以后，  该issue的updated time 就变成现在。 
再就不能标记为1周不活跃了。

### 🧐 解决方案 Solution

我看了下API，issue 有 event，comment 等等
可不可以按照最后comment的更新时间作过滤条件？
非常感谢开发组，可以帮忙评估下是否可行。

**Comment by xrkffgg** [comment]
可以

**Comment by sejust** [comment]
@xrkffgg  非常感谢开发组支持该功能。
还有个小疑问：如果在comment模式下，当前issue 没有comment，是否把issue本身（create time）当作最新时间？

**Comment by xrkffgg** [comment]
0 - 0

**Comment by xrkffgg** [comment]
来个 PR ?~
