### ISSUE TITLE
[BUG] Report bug

### ISSUE THREAD

**Issue by sejust** [actions-cool/issues-helper#159]
### 🐛 Bug 描述 Bug description

`check-inactive`  中使用`inactive-mode` == 'comment' 时，如当前 issue 没有comment，是否可以把issue本身（create time）当作最新时间？

### 🏞 期望结果 Desired result
`inactive-mode` == 'comment' 无comment时，用issue create time

### 🚑 其他信息 Other information
#157

**Comment by xrkffgg** [comment]
默认 update 不变，再新加个，如 `issue-create` 之类的
