### ISSUE TITLE
[BUG] GITHUB_TOKEN not working for GH Enterprise

### ISSUE THREAD

**Issue by x0341** [actions-cool/issues-helper#194]
### 🐛 Bug 描述 Bug description

All the actions are failing in GH Enterprise. Althought all the permissions are working for other github actions. We even add all the permissions for a PAT token.

      - name: Update Issue title
        uses: actions-cool/issues-helper@v3.6.0 
        with:
          actions: 'update-issue'
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          state: 'open'
          title: "TEST: ${{ github.event.issue.title }}"
          update-mode: 'replace'
          labels: 'New-Label'
          
### 🏞 期望结果 Desired result
New title assigned.

New title assigned.

### 🚑 其他信息 Other information

RESULTS:

Run actions-cool/issues-helper@v3.6.0
  with:
    actions: update-issue
    repo: org/repo
    token: ***
    issue-number: xxxx
    state: open
    title: TEST: sddsdsd
    update-mode: replace
    labels: New-Label
    
[📝 AC] [Init] [org/repo => [4]
**Error: [🚨 AC] Bad credentials**

**Comment by xrkffgg** [comment]
@Wxh16144 @ajuner try?
