### ISSUE TITLE
[Feature] Follow semantic versioning?

### ISSUE THREAD

**Issue by fisker** [actions-cool/issues-helper#53]
### 🥰 需求描述 Description of Requirement

Suggest follow semantic versioning, I'm not sure if dependabot can understand the version `v2`, `v2.1`.

`dependabot` can keep Github Actions up to date.

### 🧐 解决方案 Solution

Use `v2.0.0`  instead of `v2`

### 🚑 其他信息 Other information

N/A

**Comment by xrkffgg** [comment]
Necessary

**Comment by xrkffgg** [comment]
```
- name: Issues Helper
  uses: actions-cool/issues-helper@v2.0.0
```

**Comment by xrkffgg** [comment]
v2 后，会一直保持 3级语义化版本 进行发布

**Comment by fisker** [comment]
Thanks.
