### ISSUE TITLE
[Question] Is it possible to exclude issues with some labels when check-inactive ?

### ISSUE THREAD

**Issue by meteorlxy** [actions-cool/issues-helper#73]
### 🧐 问题描述 Problem Description

When using `check-inactive` action, I want to exclude issues which are marked as `bug` or some other labels.

According to the docs, the `labels` option means to "include some labels" instead of "exclude some labels":

https://github.com/actions-cool/issues-helper/blob/d443509c478af937708672ddfd3802cdab308f7b/docs/advanced.en-US.md#L48

So I wonder if it is supported to exclude issues with some labels when `check-inactive` ?

**Comment by xrkffgg** [comment]
see https://github.com/ant-design/ant-design/blob/master/.github/workflows/issue-check-inactive.yml
